status:
  Value:
    VeryLow: 20
    Low: 15
    Medium: 10
    High: 5
  Text:
    VeryLow: "VeryLow"
    Low: "Low"
    Medium: "Medium"
    High: "High"
    VeryHigh: "VeryHigh"
  LoadText: "Load : "

MaxTPS: 20

WarnTPS: 18

#Discord Webhook
WebhookURL: ""
#Discord Embed Color
EmbedColor: 12915218
Discord: false

ServerLog: true

playerListText: "Player List"
playerNameText: "Name"
playerWorldText: "World"
playerLocationText: "Location"
playerUUIDText: "UUID"

playerList: true
World: true
Location: true
UUID: false

tick: 600