status:
  Value:
    VeryLow: 20
    Low: 15
    Medium: 10
    High: 5
  Text:
    VeryLow: "最低"
    Low: "低"
    Medium: "中"
    High: "高"
    VeryHigh: "最高"
  LoadText: "負荷 : "

#最大TPS
MaxTPS: 20

WarnTPS: 18 #TPSが いくつ以下になったらTPSの情報を送信するか

#DiscordのWebhook
WebhookURL: ""
Discord: false #DiscordにTPSを送信するかどうか
Log: true #ログにTPSを送信するかどうか

playerListText: "現在サーバーにいるプレイヤー : "
playerList: true
UUID: true

#何tickに1回TPSを計測するか
tick: 300